const params=new URLSearchParams(location.search);if(params.get("embed")==="1")document.body.classList.add("embed");
const els={search:document.querySelector("#search"),industry:document.querySelector("#industry"),type:document.querySelector("#type"),keyword:document.querySelector("#keyword"),list:document.querySelector("#list"),count:document.querySelector("#resultCount"),empty:document.querySelector("#empty"),total:document.querySelector("#total"),clear:document.querySelector("#clear")};let rows=[];
function parseCSV(text){const out=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"'){q=false}else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=""}else if(c==='\n'){row.push(cell);out.push(row);row=[];cell=""}else if(c!=='\r')cell+=c}}if(cell.length||row.length){row.push(cell);out.push(row)}return out}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function split(v){return String(v||"").split(";").map(x=>x.trim()).filter(Boolean)}
function uniq(values){return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function option(el,v){const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)}
function populate(){uniq(rows.flatMap(r=>split(r.industries))).forEach(v=>option(els.industry,v));uniq(rows.map(r=>r.resource_type)).forEach(v=>option(els.type,v));uniq(rows.flatMap(r=>split(r.keywords))).forEach(v=>option(els.keyword,v))}
function haystack(r){return[r.name,r.description,r.resource_type,r.industries,r.keywords].join(" ").toLowerCase()}
function render(){const q=els.search.value.trim().toLowerCase(),industry=els.industry.value,type=els.type.value,keyword=els.keyword.value;const filtered=rows.filter(r=>(!q||haystack(r).includes(q))&&(!industry||split(r.industries).includes(industry))&&(!type||r.resource_type===type)&&(!keyword||split(r.keywords).includes(keyword)));els.list.innerHTML=filtered.map(r=>`<article class="resource"><h2>${esc(r.name)}</h2><p class="description">${esc(r.description||"")}</p><div class="taxonomy"><span><strong>${esc(r.resource_type)}</strong></span><span>${esc(r.industries)}</span></div><a class="visit" href="${esc(r.url)}" target="_blank" rel="noopener" aria-label="Open ${esc(r.name)}">↗</a></article>`).join("");els.count.textContent=`${filtered.length} of ${rows.length} resources`;els.empty.hidden=filtered.length!==0}
fetch("./data/resources.csv",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("Could not load directory");return r.text()}).then(text=>{const parsed=parseCSV(text),head=parsed.shift();rows=parsed.filter(r=>r.length&&r[0]).map(r=>Object.fromEntries(head.map((h,i)=>[h,r[i]||""]))).sort((a,b)=>a.name.localeCompare(b.name));els.total.textContent=rows.length;populate();render()}).catch(e=>{els.count.textContent=e.message});
[els.search,els.industry,els.type,els.keyword].forEach(el=>el.addEventListener("input",render));els.clear.addEventListener("click",()=>{els.search.value="";els.industry.value="";els.type.value="";els.keyword.value="";render();els.search.focus()});
