const params=new URLSearchParams(location.search);if(params.get("embed")==="1")document.body.classList.add("embed");
const els={search:document.querySelector("#search"),region:document.querySelector("#region"),format:document.querySelector("#format"),keyword:document.querySelector("#keyword"),list:document.querySelector("#list"),count:document.querySelector("#resultCount"),empty:document.querySelector("#empty"),total:document.querySelector("#total"),clear:document.querySelector("#clear")};let rows=[];
function parseCSV(text){const out=[];let row=[],cell="",q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"'){q=false}else cell+=c}else{if(c==='"')q=true;else if(c===','){row.push(cell);cell=""}else if(c==='\n'){row.push(cell);out.push(row);row=[];cell=""}else if(c!=='\r')cell+=c}}if(cell.length||row.length){row.push(cell);out.push(row)}return out}
function esc(s=""){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function split(v){return String(v||"").split(";").map(x=>x.trim()).filter(Boolean)}
function uniq(a){return[...new Set(a.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}
function add(el,v){const o=document.createElement("option");o.value=v;o.textContent=v;el.appendChild(o)}
function populate(){uniq(rows.map(r=>r.region)).forEach(v=>add(els.region,v));uniq(rows.map(r=>r.format)).forEach(v=>add(els.format,v));uniq(rows.flatMap(r=>split(r.keywords))).forEach(v=>add(els.keyword,v))}
function render(){const q=els.search.value.toLowerCase().trim(),reg=els.region.value,fmt=els.format.value,key=els.keyword.value;const filtered=rows.filter(r=>(!q||[r.name,r.city,r.country,r.description,r.keywords].join(" ").toLowerCase().includes(q))&&(!reg||r.region===reg)&&(!fmt||r.format===fmt)&&(!key||split(r.keywords).includes(key)));els.list.innerHTML=filtered.map(r=>`<article class="resource week-row"><div><h2>${esc(r.name)}</h2><p class="week-place">${esc(r.city)}, ${esc(r.country)}</p><p class="week-edition">${esc(r.edition)}</p></div><p class="week-description">${esc(r.description)}</p><div class="week-meta"><span><strong>${esc(r.region)}</strong></span><span>${esc(r.format)}</span></div><a class="visit" href="${esc(r.url)}" target="_blank" rel="noopener" aria-label="Open ${esc(r.name)}">↗</a></article>`).join("");els.count.textContent=`${filtered.length} of ${rows.length} platforms`;els.empty.hidden=filtered.length!==0}
fetch("../data/design-weeks.csv",{cache:"no-store"}).then(r=>r.text()).then(t=>{const p=parseCSV(t),h=p.shift();rows=p.filter(r=>r[0]).map(r=>Object.fromEntries(h.map((x,i)=>[x,r[i]||""]))).sort((a,b)=>a.name.localeCompare(b.name));els.total.textContent=rows.length;populate();render()});[els.search,els.region,els.format,els.keyword].forEach(e=>e.addEventListener("input",render));els.clear.addEventListener("click",()=>{els.search.value="";els.region.value="";els.format.value="";els.keyword.value="";render()});